apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: default

commonLabels:
  app: portfolio-webapp
  managed-by: kustomize

images:
- name: portfolio-webapp
  newName: portfolio-webapp
  newTag: latest
